spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mysecurity_roles_db
    username: myuser
    password: 8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect